# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
version: "2"

issues:
  max-same-issues: 0

linters:
  enable:
    - durationcheck
    - godot
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused
    - govet
    - copyloopvar
    - usetesting
  disable:
    - errcheck
    - forcetypeassert

formatters:
  enable:
    - gofmt
